gryff = House.create(name: 'Gryffindor', points: 0)
huff = House.create(name: 'Hufflepuff', points: 0)
rav = House.create(name: 'Ravenclaw', points: 0)
sly = House.create(name: 'Slytherin', points: 0)

hp = Student.create(name: 'Harry Potter', house: gryff)
rw = Student.create(name: 'Ron Weasley', house: gryff)
hg = Student.create(name: 'Hermione Granger', house: gryff)
cd = Student.create(name: 'Cedric Diggory', house: huff)
ll = Student.create(name: 'Luna Lovegood', house: rav)
dm = Student.create(name: 'Draco Malfoy', house: sly)
nl = Student.create(name: 'Neville Longbottom', house: gryff)

pmcg = Teacher.create(name: 'Minerva McGonagall', house: gryff)
sprout = Teacher.create(name: 'Pomona Sprout', house: huff)
flit = Teacher.create(name: 'Filius Flitwick', house: rav)
snape = Teacher.create(name: 'Severus Snape', house: sly)

tran = Subject.create(name: 'Transfiguration', teacher: pmcg)
herb = Subject.create(name: 'Herbology', teacher: sprout)
charms = Subject.create(name: 'Charms', teacher: flit)
pot = Subject.create(name: 'Potions', teacher: snape)

Signup.create(student: hp, subject: tran)
Signup.create(student: hg, subject: tran)
Signup.create(student: hg, subject: tran)
Signup.create(student: hp, subject: pot)
Signup.create(student: rw, subject: pot)
Signup.create(student: hg, subject: pot)
Signup.create(student: dm, subject: pot)
Signup.create(student: ll, subject: pot)
Signup.create(student: hg, subject: herb)
Signup.create(student: hg, subject: charms)
Signup.create(student: ll, subject: herb)
Signup.create(student: ll, subject: charms)
